### ISSUE TITLE
[ArgumentError] too few arguments in ruby 2.3.1

### ISSUE THREAD

**Issue by msxavi** [trailblazer/reform#404]
Hi guys,

I am struggling with this after upgrading ruby to 2.3.1 (Rails 4.2.6. Reform gem 1.2.0, I know it's old). 

Is there a way to make it works without strong impact?

     Failure/Error: form.save

     ArgumentError:
       too few arguments
     # /Users/emersonxavier/.rvm/gems/ruby-2.3.1/gems/representable-2.1.8/lib/representable/binding.rb:81:in `format'
     # /Users/emersonxavier/.rvm/gems/ruby-2.3.1/gems/representable-2.1.8/lib/representable/binding.rb:81:in `block in get'
     # /Users/emersonxavier/.rvm/gems/ruby-2.3.1/gems/representable-2.1.8/lib/representable/binding.rb:100:in `evaluate_option'
     # /Users/emersonxavier/.rvm/gems/ruby-2.3.1/gems/representable-2.1.8/lib/representable/binding.rb:80:in `get'
     # /Users/emersonxavier/.rvm/gems/ruby-2.3.1/gems/representable-2.1.8/lib/representable/binding.rb:37:in `block in compile_fragment'
     # /Users/emersonxavier/.rvm/gems/ruby-2.3.1/gems/representable-2.1.8/lib/representable/binding.rb:100:in `evaluate_option'
     # /Users/emersonxavier/.rvm/gems/ruby-2.3.1/gems/representable-2.1.8/lib/representable/binding.rb:36:in `compile_fragment'
     # /Users/emersonxavier/.rvm/gems/ruby-2.3.1/gems/representable-2.1.8/lib/representable/mapper.rb:64:in `compile_fragment'
     # /Users/emersonxavier/.rvm/gems/ruby-2.3.1/gems/representable-2.1.8/lib/representable/mapper.rb:30:in `serialize_property'
     # /Users/emersonxavier/.rvm/gems/ruby-2.3.1/gems/representable-2.1.8/lib/representable/mapper.rb:22:in `block in serialize'
     # /Users/emersonxavier/.rvm/gems/ruby-2.3.1/gems/representable-2.1.8/lib/representable/mapper.rb:21:in `each'
     # /Users/emersonxavier/.rvm/gems/ruby-2.3.1/gems/representable-2.1.8/lib/representable/mapper.rb:21:in `serialize'
     # /Users/emersonxavier/.rvm/gems/ruby-2.3.1/gems/representable-2.1.8/lib/representable.rb:41:in `create_representation_with'
     # /Users/emersonxavier/.rvm/gems/ruby-2.3.1/gems/representable-2.1.8/lib/representable/hash.rb:35:in `to_hash'
     # /Users/emersonxavier/.rvm/gems/ruby-2.3.1/gems/reform-1.2.6/lib/reform/form/sync.rb:81:in `sync_hash'
     # /Users/emersonxavier/.rvm/gems/ruby-2.3.1/gems/reform-1.2.6/lib/reform/form/sync.rb:94:in `sync_hash'
     # /Users/emersonxavier/.rvm/gems/ruby-2.3.1/gems/reform-1.2.6/lib/reform/form/sync.rb:15:in `sync!'
     # /Users/emersonxavier/.rvm/gems/ruby-2.3.1/gems/reform-1.2.6/lib/reform/form/sync.rb:6:in `sync_models'
     # /Users/emersonxavier/.rvm/gems/ruby-2.3.1/gems/reform-1.2.6/lib/reform/form/save.rb:7:in `save'
     # ./app/services/appointment_creator.rb:12:in `perform'

**Comment by apotonick** [comment]
Why such an old version of Reform? Shouldn't we rather upgrade?

**Comment by msxavi** [comment]
@apotonick started upgrading, mate.. many issues. Reform 2.0.0 for starting.

At this moment: NoMethodError: private method `binding' called for {}:Hash when invoking form.validate(parameters) method.

**Comment by apotonick** [comment]
Go straight to Reform 2.2, bro, and Representable 3.0! https://gitter.im/trailblazer/chat

**Comment by msxavi** [comment]
Eventually I will, the problem is the breaking changes all over the application. For instance, validate method has replaced update! entirely?

**Comment by msxavi** [comment]
Now reform 2.2.1 specs breaking.

```
ruby-2.3.1/gems/reform-2.2.1/lib/reform/validation.rb:6:in `validation_groups': undefined local variable or method `validation_group_class'
	from /Users/emersonxavier/.rvm/gems/ruby-2.3.1/gems/reform-2.2.1/lib/reform/validation.rb:13:in `validation'
	from /Users/emersonxavier/.rvm/gems/ruby-2.3.1/gems/reform-2.2.1/lib/reform/validation.rb:19:in `validates'
	from /Users/emersonxavier/.rvm/gems/ruby-2.3.1/gems/reform-2.2.1/lib/reform/contract.rb:24:in `property'
	from /Users/emersonxavier/.rvm/gems/ruby-2.3.1/gems/reform-2.2.1/lib/reform/form.rb:19:in `property'
	from /Users/emersonxavier/Code/neptune/app/forms/admin/expense_payment_type_form.rb:3:in `<class:ExpensePaymentTypeForm>'
	from /Users/emersonxavier/Code/neptune/app/forms/admin/expense_payment_type_form.rb:2:in `<module:Admin>'
	from /Users/emersonxavier/Code/neptune/app/forms/admin/expense_payment_type_form.rb:1:in `<top (required)>'
	from /Users/emersonxavier/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
	from /Users/emersonxavier/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `block in require'
	from /Users/emersonxavier/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/emersonxavier/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
	from /Users/emersonxavier/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:360:in `require_or_load'
	from /Users/emersonxavier/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:494:in `load_missing_constant'
	from /Users/emersonxavier/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:184:in `const_missing'
	from /Users/emersonxavier/Code/neptune/spec/forms/admin/expense_payment_type_form_spec.rb:3:in `<top (required)>'
	from /Users/emersonxavier/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `load'
	from /Users/emersonxavier/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `block in load'
	from /Users/emersonxavier/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/emersonxavier/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `load'
	from /Users/emersonxavier/.rvm/gems/ruby-2.3.1/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1361:in `block in load_spec_files'
	from /Users/emersonxavier/.rvm/gems/ruby-2.3.1/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1359:in `each'
	from /Users/emersonxavier/.rvm/gems/ruby-2.3.1/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1359:in `load_spec_files'
	from /Users/emersonxavier/.rvm/gems/ruby-2.3.1/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:106:in `setup'
	from /Users/emersonxavier/.rvm/gems/ruby-2.3.1/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:92:in `run'
	from /Users/emersonxavier/.rvm/gems/ruby-2.3.1/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:78:in `run'
	from /Users/emersonxavier/.rvm/gems/ruby-2.3.1/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:45:in `invoke'
	from /Users/emersonxavier/.rvm/gems/ruby-2.3.1/gems/rspec-core-3.4.4/exe/rspec:4:in `<top (required)>'
```

**Comment by msxavi** [comment]
Now I couldn't go on with this one:

```
Failure/Error: if @form.validate(params)
     NoMethodError:
       undefined method `call' for Date:Class
       Did you mean?  caller
     # /Users/emersonxavier/.rvm/gems/ruby-2.3.1/gems/disposable-0.3.2/lib/disposable/twin/coercion.rb:20:in `block (2 levels) in coercing_setter!'
     # /Users/emersonxavier/.rvm/gems/ruby-2.3.1/gems/representable-3.0.0/lib/representable/deserializer.rb:91:in `block in <module:Representable>'
     # /Users/emersonxavier/.rvm/gems/ruby-2.3.1/gems/representable-3.0.0/lib/representable/pipeline.rb:18:in `evaluate'
     # /Users/emersonxavier/.rvm/gems/ruby-2.3.1/gems/representable-3.0.0/lib/representable/pipeline.rb:10:in `block in call'
     # /Users/emersonxavier/.rvm/gems/ruby-2.3.1/gems/representable-3.0.0/lib/representable/pipeline.rb:9:in `each'
     # /Users/emersonxavier/.rvm/gems/ruby-2.3.1/gems/representable-3.0.0/lib/representable/pipeline.rb:9:in `inject'
     # /Users/emersonxavier/.rvm/gems/ruby-2.3.1/gems/representable-3.0.0/lib/representable/pipeline.rb:9:in `call'
     # /Users/emersonxavier/.rvm/gems/ruby-2.3.1/gems/representable-3.0.0/lib/representable/binding.rb:37:in `uncompile_fragment'
     # /Users/emersonxavier/.rvm/gems/ruby-2.3.1/gems/representable-3.0.0/lib/representable.rb:52:in `block in call'
     # /Users/emersonxavier/.rvm/gems/ruby-2.3.1/gems/representable-3.0.0/lib/representable.rb:50:in `each'
     # /Users/emersonxavier/.rvm/gems/ruby-2.3.1/gems/representable-3.0.0/lib/representable.rb:50:in `call'
     # /Users/emersonxavier/.rvm/gems/ruby-2.3.1/gems/representable-3.0.0/lib/representable.rb:69:in `representable_map!'
     # /Users/emersonxavier/.rvm/gems/ruby-2.3.1/gems/representable-3.0.0/lib/representable.rb:36:in `update_properties_from'
     # /Users/emersonxavier/.rvm/gems/ruby-2.3.1/gems/representable-3.0.0/lib/representable/hash/allow_symbols.rb:10:in `update_properties_from'
     # /Users/emersonxavier/.rvm/gems/ruby-2.3.1/gems/representable-3.0.0/lib/representable/hash.rb:30:in `from_hash'
     # /Users/emersonxavier/.rvm/gems/ruby-2.3.1/gems/reform-2.2.1/lib/reform/form/validate.rb:28:in `deserialize'
     # /Users/emersonxavier/.rvm/gems/ruby-2.3.1/gems/reform-2.2.1/lib/reform/form/validate.rb:21:in `validate'
     # ./app/controllers/placements/next_post_placement_schedule_controller.rb:13:in `update'
     # /Users/emersonxavier/.rvm/gems/ruby-2.3.1/gems/actionpack-4.2.6/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
     # /Users/emersonxavier/.rvm/gems/ruby-2.3.1/gems/actionpack-4.2.6/lib/abstract_controller/base.rb:198:in `process_action'
     # /Users/emersonxavier/.rvm/gems/ruby-2.3.1/gems/actionpack-4.2.6/lib/action_controller/metal/rendering.rb:10:in `process_action'
     # /Users/emersonxavier/.rvm/gems/ruby-2.3.1/gems/actionpack-4.2.6/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
     # /Users/emersonxavier/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:117:in `call'
     # /Users/emersonxavier/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
     # /Users/emersonxavier/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:505:in `call'
     # /Users/emersonxavier/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
     # /Users/emersonxavier/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
     # /Users/emersonxavier/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:81:in `run_callbacks'
     # /Users/emersonxavier/.rvm/gems/ruby-2.3.1/gems/actionpack-4.2.6/lib/abstract_controller/callbacks.rb:19:in `process_action'
     # /Users/emersonxavier/.rvm/gems/ruby-2.3.1/gems/actionpack-4.2.6/lib/action_controller/metal/rescue.rb:29:in `process_action'
     # /Users/emersonxavier/.rvm/gems/ruby-2.3.1/gems/actionpack-4.2.6/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
     # /Users/emersonxavier/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.6/lib/active_support/notifications.rb:164:in `block in instrument'
     # /Users/emersonxavier/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.6/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
     # /Users/emersonxavier/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.6/lib/active_support/notifications.rb:164:in `instrument'
     # /Users/emersonxavier/.rvm/gems/ruby-2.3.1/gems/actionpack-4.2.6/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
     # /Users/emersonxavier/.rvm/gems/ruby-2.3.1/gems/actionpack-4.2.6/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
     # /Users/emersonxavier/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.6/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
     # /Users/emersonxavier/.rvm/gems/ruby-2.3.1/gems/actionpack-4.2.6/lib/abstract_controller/base.rb:137:in `process'
     # /Users/emersonxavier/.rvm/gems/ruby-2.3.1/gems/actionview-4.2.6/lib/action_view/rendering.rb:30:in `process'
     # /Users/emersonxavier/.rvm/gems/ruby-2.3.1/gems/actionpack-4.2.6/lib/action_controller/test_case.rb:639:in `process'
     # /Users/emersonxavier/.rvm/gems/ruby-2.3.1/gems/actionpack-4.2.6/lib/action_controller/test_case.rb:67:in `process'
     # /Users/emersonxavier/.rvm/gems/ruby-2.3.1/gems/central-1.0.1/lib/central/test_helpers.rb:19:in `block in process'
     # /Users/emersonxavier/.rvm/gems/ruby-2.3.1/gems/central-1.0.1/lib/central/test_helpers.rb:69:in `catch'
     # /Users/emersonxavier/.rvm/gems/ruby-2.3.1/gems/central-1.0.1/lib/central/test_helpers.rb:69:in `_catch_warden'
     # /Users/emersonxavier/.rvm/gems/ruby-2.3.1/gems/central-1.0.1/lib/central/test_helpers.rb:19:in `process'
     # /Users/emersonxavier/.rvm/gems/ruby-2.3.1/gems/actionpack-4.2.6/lib/action_controller/test_case.rb:526:in `patch'
     # /Users/emersonxavier/.rvm/gems/ruby-2.3.1/gems/actionpack-4.2.6/lib/action_controller/test_case.rb:550:in `xml_http_request'
     # ./spec/controllers/placements/next_post_placement_schedule_controller_spec.rb:40:in `block (3 levels) in <top (required)>'
```

**Comment by apotonick** [comment]
Coercion now needs dry-types! http://trailblazer.to/gems/reform/options.html#coercion

**Comment by fran-worley** [comment]
Have you checked out http://trailblazer.to/gems/reform/upgrading-guide.html ?

**Comment by msxavi** [comment]
@apotonick Have you already dropped support for reform 1.2?

**Comment by apotonick** [comment]
Of course, it's a few years old. I can offer you upgrading support: http://trailblazer.to/inc/help.html

**Comment by fran-worley** [comment]
I'm going to close this as we no longer provide support for such an old version of Reform. I hope that you have managed to resolve your issue. If not try the gitter channel or take @apotonick up on his offer.
